apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-php
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}-php
    spec:
      containers:
        - name: main
          image: {{ required ".Values.image is required" .Values.image }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: REDIS
              value: {{ .Release.Name }}-redis
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
