apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  replicas: {{ .Values.frontendReplicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: main
          image: {{ .Values.frontendImage }}
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 300Mi
          env:
            - name: API_ORIGIN
              value: http://{{ .Release.Name }}-backend
          {{ if .Values.frontendEnvSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.frontendEnvSecret }}
          {{ end }}
          ports:
            - containerPort: 3000
